### ISSUE TITLE
Ребята, это не серьёзно - cэмплы под старое SDK

### ISSUE THREAD

**Issue by crea7or** [yandexmobile/metrica-sample-dotnet#11]
metrica-sample-dotnet/Yandex.Metrica.Samples/Yandex.Metrica.WP8/
App.xaml.cs -> YandexMetrica.ReportExit(); нет такого метода.

App.xaml -> metrica1:Bootstrapper тоже нет, надо metrica1:YandexMetricaActivator. Хотя не работает даже так: Error 1 Unable to determine application identity of the caller.

Сэмпл под SDK 2.2 а у вас уже давно 3.2 вышел. 

И на странице документации неработающая лажа:
https://tech.yandex.ru/metrica-mobile-sdk/doc/mobile-sdk-dg/tasks/winphone-quickstart-docpage/

**Comment by Makeloft** [comment]
Здравствуйте! Спасибо за интерес к _AppMetrica_!

Сэмплы обновили. Метод _ReportExit_ удалён в новых версиях библиотеки.
_YandexMetricaActivato_r работает, проект компилируется несмотря на то , что _Visual Studio_ может выдавать ту ошибку, о которой выписали. В новой версии этот нюанс исправим.
