### ISSUE TITLE
Крэши при разрешённой геолокации на Windows 10

### ISSUE THREAD

**Issue by oiuldashov** [yandexmobile/metrica-sample-dotnet#14]
Здравствуйте.

Приложение крэшится при разрешённой геолокации для приложения.
Приложение написано под Windows 8.1 и запускается в Windows 10.
Если выключить геолокацию (Start Menu > Settings > Privacy > Location) для приложения, то всё ок.

Метрика показывает такую ошибку:

`System.InvalidOperationException: Nullable object must have a value. at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource) at Yandex.Metrica.DTO.ReportMessage.Location..ctor(Geocoordinate geocoordinate) at Yandex.Metrica.Platform.Wp8SingleShotLocationProvider.<StartUpdatingLocation>b__1(Geolocator geolocator, PositionChangedEventArgs eventArgs)`

**Comment by Makeloft** [comment]
Здравствуйте! Судя по названию класса Wp8SingleShotLocationProvider, вы используете в своём приложении старое поколение метрики 2.x. Попробуйте обновиться на новое 3.x.
Если это не исправит проблему, то дайте нам, пожалуйста, знать.

Спасибо за обратную связь!

**Comment by oiuldashov** [comment]
Обновился.
Всё равно падает.

System.ArgumentNullException was unhandled
Message: An unhandled exception of type 'System.ArgumentNullException' occurred in Yandex.Metrica.RT8.1.DLL
Additional information: Value cannot be null.

Stack trace:
   at System.Threading.Monitor.Enter(Object obj)
   at Yandex.Metrica.LiteMetricaCore.Lull()
   at Yandex.Metrica.LiteMetricaService.Finalize()

**Comment by Makeloft** [comment]
Здесь уже в чём-то другом проблема. Вы говорили, что приложение у вас для WP8.1, странно, что в проект добавилась сборка Yandex.Metrica.RT8.1.DLL. Это для Windows 8.1, для Windwos Phone 8.1 нужна Yandex.Metrica.WP8.1.DLL.

Падение происходит при запуске приложения или же в процессе работы? В каком месте вы активируете метрику?

**Comment by oiuldashov** [comment]
Судя по всему, я из метрики, в первый раз, взял не тот лог. Сейчас смотрел в VS2015. И забыл обозначить, что это декстопная винда.

Спустя несколько секунд после начала работы. Доступ, к интернету, точно есть, т.к. приложение успевает поработать.
Активирую в `protected override void OnLaunched(LaunchActivatedEventArgs e)`.

Исправляется всё так же, через отключение настроек геолокации в приложении

Могу скинуть, в течении дня, тестовый проект, если нужно.

**Comment by Makeloft** [comment]
Странно немного, но было бы полезно взглянуть на пример.
У вас в манифесте приложения установлено разрешение на получение локации?

Можете писать сюда или же на любой из этих контактов
makeman@yandex-team.ru
skype: vovka.makarevich
telegram: @vladimir_makarevich
