### ISSUE TITLE
WP8.1 applications support

### ISSUE THREAD

**Issue by kzaikin** [yandexmobile/metrica-sample-dotnet#3]
Пожалуйста, добавьте поддержку приложений WP8.1
Добавить Метрику в приложение не получается из-за зависимости от пакета Zlib.portable, которого нет для WP8.1

**Comment by alexeygritsenko** [comment]
Присоединяюсь к теме.
Вот новость http://www.3dnews.ru/904333 но сейчас их больше)
Пора бы добавить поддержку 8.1 с апи новых универсальных приложений.

**Comment by fkazak** [comment]
[В последнем релизе](http://www.nuget.org/packages/Yandex.Metrica/) была добавлена поддержка WP8.1 и универсальных приложений. Если в ней замечены какие-то проблемы - сообщайте.

**Comment by alexeygritsenko** [comment]
Добрый день, только сегодня вернулся к своему проекту, очень рад что добавили 8.1 но документацию и примеры так и не обновили(
Один из вопросов как на 8.1 называется ID_CAP_IDENTITY_DEVICE указанный здесь 
https://tech.yandex.ru/metrica-mobile-sdk/doc/mobile-sdk-dg/tasks/winphone-quickstart-docpage/
?
![ashampoo_snap_2015 03 06_12h34m49s_001_](https://cloud.githubusercontent.com/assets/10233486/6523068/3a4e8856-c3fd-11e4-997f-bb47d84f17bd.png)
