### ISSUE TITLE
Обновите исходники

### ISSUE THREAD

**Issue by crea7or** [yandexmobile/metrica-sample-dotnet#4]
Поменяли ведь API, а сэмплы старые: metrika:CounterBootstrapper -> metrika:Bootstrapper

**Comment by jenokizm** [comment]
crea7or вроде исправили)
я смотрю и под универсальные документация появилась https://tech.yandex.ru/metrica-mobile-sdk/doc/mobile-sdk-dg/tasks/winstore-quickstart-docpage/
надо попробывать) 
пс правильно называть такие приложение не Windows Store а windows universal apps) ох уж эти яндекс разработчики....

**Comment by jenokizm** [comment]
пс яндекс, у вас нет аналога admob? было бы супер....

**Comment by crea7or** [comment]
да ничего пока не исправили:
https://github.com/yandexmobile/metrica-sample-dotnet/blob/master/Yandex.Metrica.Sample.wp8/App.xaml

**Comment by jenokizm** [comment]
а... ты про семплы, я думал доки на их сайте)
да семплы мало того что старые не обновили, так еще и поленились для вп8.1 универсального сделать((

**Comment by yvasileuski** [comment]
исправлено

**Comment by jenokizm** [comment]
да уж)) ребята идут в ногу со временем) такими шагами через год можно ждать примеров для десятки)
