### ISSUE TITLE
Ошибка и замечания

### ISSUE THREAD

**Issue by alexeygritsenko** [yandexmobile/metrica-sample-dotnet#5]
![ashampoo_snap_2015 06 19_18h37m37s_001_](https://cloud.githubusercontent.com/assets/10233486/8256834/50899ffe-16b2-11e5-9864-cacdee04e44d.png)
1. Метрика работает, но некая ошибка мозолит глаза(
> Ошибка	1	Error HRESULT E_FAIL has been returned from a call to a COM component.	c:\users\alexey\documents\visual studio 2013\Projects\MyTestApp1\MyTestApp1\App.xaml	11	13	MyTestApp1

2. Экран 800x480 определил как 800x479 - сделайте корректировки
3. Не определил оператора Билайн. Сделать это проще простого... Дорабатывайте...

**Comment by yvasileuski** [comment]
должно исправиться в новой версии АппМетрика 2.0
