### ISSUE TITLE
Windows Store 10 and C++/CLI version.

### ISSUE THREAD

**Issue by perminovVS** [yandexmobile/metrica-sample-dotnet#8]
Яндекс планирует обновить библиотеку для поддержки Windows Store 10 приложений ?
Почему бы так же не создать сборку, в виде C++/CLI обертки, для использования в классических приложениях ?
Если нет, то почему бы не отрыть исходники / или api по обмену данными с метрикой.

**Comment by alexeygritsenko** [comment]
Библиотека уже как 2 месяца обновлена и поддерживает вин10. Единственно это не указано в документации.
Насчет остального пусть отвечают представители яндекса) а отвечают они долго)

**Comment by Makeloft** [comment]
AppMetrica 3x поддерживает UWP-приложения, в том числе для Windows 10.
